name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    name: Build and Push Commit
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Check if Build Branch Exists
        run: |
          if git rev-parse --verify build >/dev/null 2>&1; then
            echo "Build branch already exists. Checking out existing build branch."
            git checkout build
          else
            echo "Build branch does not exist. Creating a new build branch."
            # git checkout -b build
            git fetch origin build:build
            git checkout build
          fi

      - name: Merge main -> build
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: build
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Asset
        run: npm run build # The build command of your project
    
      - name: Create commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: [Auto] Build asset