# .github/workflows/release.yml
name: Push to remote server

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Make commit
    steps:
      - name: Check Tag Format
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Not a valid release tag. Exiting..."
            exit 0
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if Build Branch Exists
        run: |
          if git rev-parse --verify build >/dev/null 2>&1; then
            echo "Buld branch already exists."
          else
            echo "Build branch does not exist. No source branch to make PR."
            exit 0
          fi

      - name: Check if Release Branch Exists
        run: |
          if git rev-parse --verify release >/dev/null 2>&1; then
            echo "Release branch already exists."
          else
            echo "Release branch does not exist. Creating a new release branch."
            exit 0
          fi
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update Release
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: release
          base: build
          delete-branch: false
          body: |
            Update release based on recent build

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"